apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: food-app
    name: food-app
spec:
   replicas: 3
   selector:
      matchLabels:
          app: food-app
   template: 
     metadata:
       labels:
         app: food-app
     spec:
      containers:
       - name: food-app
         image: 170037050693.dkr.ecr.ap-south-1.amazonaws.com/app1:65674ef02307e185a52349fd1ae62c65a9bd6d1c
         ports:
          - containerPort: 80
