apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv
   namespace: food-app
spec:
  accessModes:
    - ReadWriteOnce 
  reclaimPolicy: retain
  storageClassName: normal
  capacity:
    storage: 2Gi
  hostPath: 
    path: /data
