apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: food-app-pvc
  namespace: food-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
