name: git with terraform

on:
 workflow_dispatch:
env:
  AWS_REGION: ap-south-1
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:

     - name: Checkout Code
       uses: actions/checkout@v4
      
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 
  
     - name: create s3 bucket
       run: |
        cd bootstrap
        terraform init
        terraform apply -auto-approve

     - name: terraform init and apply
       run: |
         cd terraform-files
         terraform init -reconfigure
         terraform apply -auto-approve   

     - name: Login to ECR
       uses: aws-actions/amazon-ecr-login@v2
  
     - name: Build Docker image
       run: |
          cd app/
          docker build -t app1:${{ github.sha }} .

     - name: Tag image
       run: docker tag app1:${{ github.sha }} ${{ secrets.REPOSITORY_URL }}:${{ github.sha }}

     - name: Push image to ECR
       run: docker push "${REPOSITORY_URL}:${COMMIT_ID}"
