name: git with terraform

on:
 push:
    branches:
      - main
env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:

     - name: Checkout Code
       uses: actions/checkout@v4
      
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
  
     - name: terraform init
       run: |
        cd terraform-files
        terraform init
     - name: terraform apply
       run: |
        cd terraform-files
        tereraform apply -auto-approve

     - name: Login to ECR
       uses: aws-actions/amazon-ecr-login@v2
  
     - name: Build Docker Image
       run: |
          docker build -t image ./app
          docker tag image:latest ${{ secrets.AWS_ACCESS_KEY_ID }}.dkr.ecr.${{ secrets.AWS_SECRET_ACCESS_KEY }}.amazonaws.com/${{ image } }}:latest

     - name: Push image to ECR
       run:  docker push ${{ secrets.AWS_ACCESS_KEY_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ git with iac }}:latest
